#!/bin/sh

PATH=/bin:/usr/bin:/tools/bin:/tools/sbin
time=5
MSG="Bisonte is rebooting in $time seconds (with forcefsck)."

touch /etc/runit/rbootfsckf
touch /etc/runit/stopit
echo $MSG
chmod 100 /etc/runit/stopit && echo "$MSG" | wall
sleep $time 
