" Begin /etc/vimrc
" Ensure defaults are set before customizing settings, not after
source $VIMRUNTIME/defaults.vim
let skip_defaults_vim=1
set nocompatible
set backspace=2
set mouse=
syntax on

if (&term == "xterm") || (&term == "putty")
set background=dark
endif

set spelllang=es,en
map <f12> :set spell!<cr>
"this is to activate/deactivate the spelling

set tw=75 et nowritebackup

" End /etc/vimrc
